# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: plan_gcp_tf
    displayName: "Planning GCP resource using tf"
    jobs:
      - job: planingtf
        pool:
          vmImage:'windows-latest'
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '0.12.2'