# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: GCP_TF_Deploy
    displayName: "Planning GCP resource using tf"
    jobs:
      - job: planing_tf
        pool:
          name: 'Azure Pipelines'
          vmImage:  'windows-latest'
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '0.12.16'
          - task: TerraformCLI@0
            displayName: 'Initializing Terraform'
            env:
              GOOGLE_CREDENTIALS: $(google_credentials)
              BILLING_AC_ID: $(billing_ac_id)
            inputs:
              command: 'init'
          - task: PowerShell@2
            displayName: 'Terraform Plan'
            env:
              GOOGLE_CREDENTIALS: $(google_credentials)
              BILLING_AC_ID: $(billing_ac_id)
            inputs:
              targetType: 'inline'
              script: |
                # terraform plan.
                
                terraform plan -var project_id=$env:project_id -var billing_ac_id=$env:billing_ac_id
  - stage: 'deploy_tf'
    displayName: "deploy tf resources in GCP"
    jobs:
    - deployment: 'deploytf'
      environment: GCP_Demo
      pool:
          name: 'Azure Pipelines'
          vmImage:  'windows-latest'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: TerraformInstaller@0
              inputs:
                terraformVersion: '0.12.16'
            - task: TerraformCLI@0
              displayName: 'Initializing Terraform'
              env:
                GOOGLE_CREDENTIALS: $(google_credentials)
                BILLING_AC_ID: $(billing_ac_id)
              inputs:
                command: 'init'
            - task: PowerShell@2
              inputs:
                targetType: 'inline'
                script: |
                  # Write your PowerShell commands here.
                  
                  Get-ChildItem $(System.ArtifactsDirectory)
            - task: PowerShell@2
              enabled: False
              env:
                GOOGLE_CREDENTIALS: $(google_credentials)
                BILLING_AC_ID: $(billing_ac_id)
              inputs:
                targetType: 'inline'
                script: |
                  # terraform apply
                  terraform apply -var project_id=$env:project_id -var billing_ac_id=$env:billing_ac_id -auto-approve
